/content/documents/gogreen/products:
  .meta:order-before: newsfacets
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 95fc495e-a8b6-4810-aa86-f4b377985d48
  hippostd:foldertype: [new-translated-folder, new-document]
  hippotranslation:id: 310a06aa-b0c1-4056-a348-4af90a637b5b
  hippotranslation:locale: en
  /solar-centurian---outdoor-security-light:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'mix:referenceable']
    jcr:uuid: cd7c2d69-e191-4ce7-a67d-48a88bba1c22
    hippo:name: Solar Centurian - Outdoor Security Light
    /solar-centurian---outdoor-security-light[1]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 62c2832c-942d-42ca-a8bc-b6bffc9eb013
      gogreen:introduction: Light up your night with a solar powered, motion detected
        outdoor security light!
      gogreen:price: 74.0
      gogreen:title: Solar Centurian - Outdoor Security Light
      hippo:availability: []
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2017-09-13T14:02:52.625-07:00
      hippostdpubwf:lastModificationDate: 2017-09-13T14:02:52.625-07:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 94c0e912-f101-48ca-ac81-1a2c5bd5874e
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>This solar powered light is a bright (over 600 lumen) Halogen Security Light that installs easily where utility wiring is impractical or expensive. A patented passive infrared motion detector is able to detect activity up to 23m/75 feet away controls the light. When activated, the Solar Centurion throws a flood light into the target area for up to 3 minutes or as long as there is movement in the area.</p>

          <p>It is perfect for security lighting or convenience lighting in your yard, at your garage, around your garage, or wherever security lighting is required at night!</p>

          <p>The light is replaceable at any lighting or hardware store (Sylvania 1995/ERK miniature Halogen Lamp).</p>

          <p>© Green Home, Inc.<br />
          <a href="http://www.greenhome.com/products/yard_and_garden/outdoor_lighting/109508/">http://www.greenhome.com/products/yard_and_garden/outdoor_lighting/109508/</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4ca2c809-401a-4f3f-b155-4dd63defef2c
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /solar-centurian---outdoor-security-light[2]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
      jcr:uuid: 3ab63c82-9df2-436a-86e7-07528f432b19
      gogreen:introduction: Light up your night with a solar powered, motion detected
        outdoor security light!
      gogreen:price: 74.0
      gogreen:title: Solar Centurian - Outdoor Security Light
      hippo:availability: [preview]
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2017-09-13T14:02:52.625-07:00
      hippostdpubwf:lastModificationDate: 2017-09-13T14:03:27.989-07:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 94c0e912-f101-48ca-ac81-1a2c5bd5874e
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>This solar powered light is a bright (over 600 lumen) Halogen Security Light that installs easily where utility wiring is impractical or expensive. A patented passive infrared motion detector is able to detect activity up to 23m/75 feet away controls the light. When activated, the Solar Centurion throws a flood light into the target area for up to 3 minutes or as long as there is movement in the area.</p>

          <p>It is perfect for security lighting or convenience lighting in your yard, at your garage, around your garage, or wherever security lighting is required at night!</p>

          <p>The light is replaceable at any lighting or hardware store (Sylvania 1995/ERK miniature Halogen Lamp).</p>

          <p>© Green Home, Inc.<br />
          <a href="http://www.greenhome.com/products/yard_and_garden/outdoor_lighting/109508/">http://www.greenhome.com/products/yard_and_garden/outdoor_lighting/109508/</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4ca2c809-401a-4f3f-b155-4dd63defef2c
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /solar-centurian---outdoor-security-light[3]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 253e27b4-e933-4d5d-86a7-1abf3e8f49b8
      gogreen:introduction: Light up your night with a solar powered, motion detected
        outdoor security light!
      gogreen:price: 74.0
      gogreen:title: Solar Centurian - Outdoor Security Light
      hippo:availability: [live]
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2017-09-13T14:02:52.625-07:00
      hippostdpubwf:lastModificationDate: 2017-09-13T14:03:27.989-07:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2017-09-13T14:03:29.499-07:00
      hippotranslation:id: 94c0e912-f101-48ca-ac81-1a2c5bd5874e
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>This solar powered light is a bright (over 600 lumen) Halogen Security Light that installs easily where utility wiring is impractical or expensive. A patented passive infrared motion detector is able to detect activity up to 23m/75 feet away controls the light. When activated, the Solar Centurion throws a flood light into the target area for up to 3 minutes or as long as there is movement in the area.</p>

          <p>It is perfect for security lighting or convenience lighting in your yard, at your garage, around your garage, or wherever security lighting is required at night!</p>

          <p>The light is replaceable at any lighting or hardware store (Sylvania 1995/ERK miniature Halogen Lamp).</p>

          <p>© Green Home, Inc.<br />
          <a href="http://www.greenhome.com/products/yard_and_garden/outdoor_lighting/109508/">http://www.greenhome.com/products/yard_and_garden/outdoor_lighting/109508/</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4ca2c809-401a-4f3f-b155-4dd63defef2c
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
  /lifeproof-nuud-ipad-air-case:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'mix:referenceable']
    jcr:uuid: 9c5b71fa-8f17-4472-9cc2-6dc9f1ccb5a9
    hippo:name: Lifeproof nüüd IPad Air Case
    /lifeproof-nuud-ipad-air-case[1]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: a9cfc428-a00f-4798-8ee8-41cb32eaf2c7
      gogreen:introduction: Get full protection for your phone in any wet, dirty or
        damp setting.The nuud case armours your iPad Air without putting anything
        between your fingertips and the touchscreen. An optical glass lens lets you
        see and use the screen with crystal clarity.
      gogreen:price: 129.0
      gogreen:title: Lifeproof nüüd IPad Air Case
      hippo:availability: []
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2017-09-13T14:03:40.304-07:00
      hippostdpubwf:lastModificationDate: 2017-09-13T14:03:40.304-07:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 05d7ecbd-ef9a-4d1a-b006-b812a5317a18
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>&nbsp;</p>

          <ul>
           <li>Waterproof, fully submersible to 2 metres for up to 1 hour.</li>
           <li>Shockproof, survives drops from 2 metres.</li>
           <li>Full access to touchscreen and all buttons, ports and controls.</li>
           <li>Maximum sound output and clarity.</li>
           <li>Anti-reflective optical-glass camera lens.</li>
           <li>Dimensions are 261.6 x 188 x 17.8mm.</li>
           <li>The LifeProof warranty and MEC's Rocksolid Guarantee cover this case itself. Neither guarantee covers the contents you put inside the case.</li>
          </ul>

          <p>© Mountain Equipment Co-operative<br />
          <a href="http://www.mec.ca/product/5038-716/lifeproof-nuud-ipad-air-case/?f=10+50007+50023">http://www.mec.ca/product/5038-716/lifeproof-nuud-ipad-air-case/?f=10+50007+50023</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 28c8c7bb-ed6b-4cbe-a5c6-5540395f3337
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /lifeproof-nuud-ipad-air-case[2]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
      jcr:uuid: e19051bd-3b62-4397-b84a-02e05bcf4c88
      gogreen:introduction: Get full protection for your phone in any wet, dirty or
        damp setting.The nuud case armours your iPad Air without putting anything
        between your fingertips and the touchscreen. An optical glass lens lets you
        see and use the screen with crystal clarity.
      gogreen:price: 129.0
      gogreen:title: Lifeproof nüüd IPad Air Case
      hippo:availability: [preview]
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2017-09-13T14:03:40.304-07:00
      hippostdpubwf:lastModificationDate: 2017-09-13T14:04:21.345-07:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 05d7ecbd-ef9a-4d1a-b006-b812a5317a18
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>&nbsp;</p>

          <ul>
           <li>Waterproof, fully submersible to 2 metres for up to 1 hour.</li>
           <li>Shockproof, survives drops from 2 metres.</li>
           <li>Full access to touchscreen and all buttons, ports and controls.</li>
           <li>Maximum sound output and clarity.</li>
           <li>Anti-reflective optical-glass camera lens.</li>
           <li>Dimensions are 261.6 x 188 x 17.8mm.</li>
           <li>The LifeProof warranty and MEC's Rocksolid Guarantee cover this case itself. Neither guarantee covers the contents you put inside the case.</li>
          </ul>

          <p>© Mountain Equipment Co-operative<br />
          <a href="http://www.mec.ca/product/5038-716/lifeproof-nuud-ipad-air-case/?f=10+50007+50023">http://www.mec.ca/product/5038-716/lifeproof-nuud-ipad-air-case/?f=10+50007+50023</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 28c8c7bb-ed6b-4cbe-a5c6-5540395f3337
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /lifeproof-nuud-ipad-air-case[3]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: b5976b0c-8364-4ed5-b460-d68553ce6bcb
      gogreen:introduction: Get full protection for your phone in any wet, dirty or
        damp setting.The nuud case armours your iPad Air without putting anything
        between your fingertips and the touchscreen. An optical glass lens lets you
        see and use the screen with crystal clarity.
      gogreen:price: 129.0
      gogreen:title: Lifeproof nüüd IPad Air Case
      hippo:availability: [live]
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2017-09-13T14:03:40.304-07:00
      hippostdpubwf:lastModificationDate: 2017-09-13T14:04:21.345-07:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2017-09-13T14:04:22.713-07:00
      hippotranslation:id: 05d7ecbd-ef9a-4d1a-b006-b812a5317a18
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>&nbsp;</p>

          <ul>
           <li>Waterproof, fully submersible to 2 metres for up to 1 hour.</li>
           <li>Shockproof, survives drops from 2 metres.</li>
           <li>Full access to touchscreen and all buttons, ports and controls.</li>
           <li>Maximum sound output and clarity.</li>
           <li>Anti-reflective optical-glass camera lens.</li>
           <li>Dimensions are 261.6 x 188 x 17.8mm.</li>
           <li>The LifeProof warranty and MEC's Rocksolid Guarantee cover this case itself. Neither guarantee covers the contents you put inside the case.</li>
          </ul>

          <p>© Mountain Equipment Co-operative<br />
          <a href="http://www.mec.ca/product/5038-716/lifeproof-nuud-ipad-air-case/?f=10+50007+50023">http://www.mec.ca/product/5038-716/lifeproof-nuud-ipad-air-case/?f=10+50007+50023</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 28c8c7bb-ed6b-4cbe-a5c6-5540395f3337
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
  /mec-lodge-4-4-tent:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'mix:referenceable']
    jcr:uuid: 6f2187de-8177-4781-a2ca-e85b7535e5bc
    hippo:name: MEC Lodge 4+4 Tent
    /mec-lodge-4-4-tent[1]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 142cc2b0-2e4c-4f5f-888a-038dfdae1c46
      gogreen:introduction: Glamping, anyone? This large tent has 2 bedrooms that
        each sleep 2 people. Both rooms are accessed from a central hall that’s tall
        enough to stand up in. The hall doesn't have a floor, so you can use it to
        deal with wet gear without getting your sleeping bags wet or gritty. Store
        your bikes in it, dry your wetsuit, or use it as a sheltered dining area.
        An optional ground sheet converts the hall to a bedroom that sleeps up to
        4 additional campers.
      gogreen:price: 589.0
      gogreen:title: MEC Lodge 4+4 Tent
      hippo:availability: []
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2017-09-13T14:04:31.758-07:00
      hippostdpubwf:lastModificationDate: 2017-09-13T14:04:31.758-07:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 0eb060c9-26c4-4212-b04e-1e63d94a4661
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <ul>
           <li>Central hall has doors with zippable mesh ventilation at either end.</li>
           <li>Hall has numerous hanging points for drying lines or lanterns.</li>
           <li>Each 2-person room has double pockets.</li>
           <li>Hall has 4 storage pockets.</li>
           <li>Optional floor for central hall available separately.</li>
          </ul>

          <p>© Mountain Equipment Co-operative<br />
          <a href="http://www.mec.ca/product/5032-207/mec-lodge-44-tent/?h=10+50055+50130&amp;f=10+50130+50858">http://www.mec.ca/product/5032-207/mec-lodge-44-tent/?h=10+50055+50130&amp;f=10+50130+50858</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: e358eefe-f74e-4e9d-b434-b57af237006a
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /mec-lodge-4-4-tent[2]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
      jcr:uuid: f38d0bc5-746a-4154-a99d-36f4ed68fac4
      gogreen:introduction: Glamping, anyone? This large tent has 2 bedrooms that
        each sleep 2 people. Both rooms are accessed from a central hall that’s tall
        enough to stand up in. The hall doesn't have a floor, so you can use it to
        deal with wet gear without getting your sleeping bags wet or gritty. Store
        your bikes in it, dry your wetsuit, or use it as a sheltered dining area.
        An optional ground sheet converts the hall to a bedroom that sleeps up to
        4 additional campers.
      gogreen:price: 589.0
      gogreen:title: MEC Lodge 4+4 Tent
      hippo:availability: [preview]
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2017-09-13T14:04:31.758-07:00
      hippostdpubwf:lastModificationDate: 2017-09-13T14:05:02.069-07:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 0eb060c9-26c4-4212-b04e-1e63d94a4661
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <ul>
           <li>Central hall has doors with zippable mesh ventilation at either end.</li>
           <li>Hall has numerous hanging points for drying lines or lanterns.</li>
           <li>Each 2-person room has double pockets.</li>
           <li>Hall has 4 storage pockets.</li>
           <li>Optional floor for central hall available separately.</li>
          </ul>

          <p>© Mountain Equipment Co-operative<br />
          <a href="http://www.mec.ca/product/5032-207/mec-lodge-44-tent/?h=10+50055+50130&amp;f=10+50130+50858">http://www.mec.ca/product/5032-207/mec-lodge-44-tent/?h=10+50055+50130&amp;f=10+50130+50858</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: e358eefe-f74e-4e9d-b434-b57af237006a
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
    /mec-lodge-4-4-tent[3]:
      jcr:primaryType: gogreen:product
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 561af24b-1872-43b8-a0ea-1ff060a99427
      gogreen:introduction: Glamping, anyone? This large tent has 2 bedrooms that
        each sleep 2 people. Both rooms are accessed from a central hall that’s tall
        enough to stand up in. The hall doesn't have a floor, so you can use it to
        deal with wet gear without getting your sleeping bags wet or gritty. Store
        your bikes in it, dry your wetsuit, or use it as a sheltered dining area.
        An optional ground sheet converts the hall to a bedroom that sleeps up to
        4 additional campers.
      gogreen:price: 589.0
      gogreen:title: MEC Lodge 4+4 Tent
      hippo:availability: [live]
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2017-09-13T14:04:31.758-07:00
      hippostdpubwf:lastModificationDate: 2017-09-13T14:05:02.069-07:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2017-09-13T14:05:03.954-07:00
      hippotranslation:id: 0eb060c9-26c4-4212-b04e-1e63d94a4661
      hippotranslation:locale: en
      /gogreen:description:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <ul>
           <li>Central hall has doors with zippable mesh ventilation at either end.</li>
           <li>Hall has numerous hanging points for drying lines or lanterns.</li>
           <li>Each 2-person room has double pockets.</li>
           <li>Hall has 4 storage pockets.</li>
           <li>Optional floor for central hall available separately.</li>
          </ul>

          <p>© Mountain Equipment Co-operative<br />
          <a href="http://www.mec.ca/product/5032-207/mec-lodge-44-tent/?h=10+50055+50130&amp;f=10+50130+50858">http://www.mec.ca/product/5032-207/mec-lodge-44-tent/?h=10+50055+50130&amp;f=10+50130+50858</a></p>
      /gogreen:images:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: e358eefe-f74e-4e9d-b434-b57af237006a
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
